"""add site_name to meters

Revision ID: 7adadfca625d
Revises: bb84e8355ce8
Create Date: 2026-06-15 19:25:44.111475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adadfca625d'
down_revision: Union[str, Sequence[str], None] = 'bb84e8355ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meters', sa.Column('site_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'site_name')
    # ### end Alembic commands ###
