"""initial_schema

Revision ID: c8f6d37afde0
Revises: 
Create Date: 2026-06-19 22:42:12.056297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f6d37afde0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recs',
    sa.Column('rec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('meter_id', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('received_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec_cabine',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('cabina_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['rec_id'], ['recs.rec_id'], ),
    sa.PrimaryKeyConstraint('rec_id', 'cabina_code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('pod', sa.String(), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.Column('threshold_kwh', sa.Float(), nullable=True),
    sa.Column('notification_interval_hours', sa.Integer(), nullable=True),
    sa.Column('last_notified_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['recs.rec_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('meters',
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('consumption_enabled', sa.Integer(), nullable=True),
    sa.Column('production_enabled', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('meter_id')
    )
    op.create_table('energy_readings',
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.meter_id'], ),
    sa.PrimaryKeyConstraint('meter_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_readings')
    op.drop_table('meters')
    op.drop_table('users')
    op.drop_table('rec_cabine')
    op.drop_table('webhook_events')
    op.drop_table('recs')
    # ### end Alembic commands ###
